name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: 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
          GIST_ID: 2756b1fb101dfda96281a371d9d1118f
          TIMEZONE: Asia/Seoul
